# Generated by Django 4.1 on 2022-10-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0002_songs_alter_books_b_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
