# Generated by Django 4.1 on 2022-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0004_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=250, unique=True)),
                ('file', models.FileField(upload_to='song')),
                ('img', models.ImageField(upload_to='imgs')),
                ('desc', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
